### ISSUE TITLE
How to create an alerting using the ELK stack(email alerting only)

### ISSUE THREAD

**Issue by hrkshyd** [HarendraKumarSingh/ELK-setup#1]
How to create an alerting using the ELK stack.
I want to create an email alerting using ELK stack ,when a log message contains any specific job failure/critical message the ELK setup should be capable of sending such log message alert. What should I use to create an alert functionality, need help to complete an in house assignment.

**Comment by HarendraKumarSingh** [comment]
Email alerting can be achieved by add below code in the logstash conf output block : - </br>

<pre><code>output {
#Below will alert on any log message containing the substring “CRITICAL” , you can use your specific message in place of “CRITICAL” to check in the log message
#So when ever you get such sub string in your log message you will be alerted with the same. you can even implement an action on any alert using the action block with in the the alert block.
 if  "CRITICAL" in [message]  {
     email {
            from => "log-mailer@XYZ.com"
            subject => “Central logstash alert"
            to => “my_email@ABC.com"
            via => "smtp"
            body => "Here is the event line that occured: %{message} \nLog file: %{path}"
            options => {
                    starttls => "true"
                    smtpIporHost => "email.XYZ.com"
                    port => "587"
                    userName => “log-mailer@XYZ.com” 
            #email-server-mail-id
                    password => “password”
                    authenticationType => "LOGIN"
            } 
         } 
    }
}
</code></pre>

NOTE : Beware of the bulk emails. It can be controlled on below conditions :</br>

<ul><li>1.Generate a single alert when something goes wrong. Don't spam.</li>
<li>2.Be able to alert on both volume of a particular message or lack thereof</br>.
Eg :(Generate an alert if there are more than 10 404s in a 5 minute period.)</br>
#only call alert if CRITICAL in log message </br></li>
 <pre><code> if "CRITICAL" in [message] {
    #generate an alert
    alert {
    max_threshold => 10
    max_threshold_msg => ‘CRITICAL’
    period => 300
    key => "CRITICAL alerts"
    }
 }</code><pre>
<li>3.If alerting on lack thereof, alert even if there was 0 messages during the period.</li></ul>

**Comment by hrkshyd** [comment]
Many Thanks Harendra..
Your post really being a great piece of code. I have completed my project using your ELK setup guide and the email alerting code.
Thanks Again for this help..

**Comment by HarendraKumarSingh** [comment]
welcome...happy coding

**Comment by tanxiaolong** [comment]
@HarendraKumarSingh  if there no key words like "CRITICAL", how could it be?
if there could be a judgement that emails me when the present value is larger than the average of last 5 values? 
thx a lot~
